version: "3.7"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: jupyterlab
    restart: always
    container_name: jupyterlab
    networks:
      spark-network:
        ipv4_address: 10.5.0.5
    ports:
      - 3306:3306
    volumes:
      - shared-workspace:/opt/workspace

  spark-master:
    image: spark-master
    restart: always
    container_name: spark-master
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      - SPARK_LOCAL_IP=spark-master

  spark-worker-1:
    image: spark-worker
    restart: always
    container_name: spark-worker-1
    hostname: spark-worker-1
    env_file: ./spark-worker.sh
    environment:
      - SPARK_LOCAL_IP=spark-worker-1
    ports:
      - 8081:8081
    networks:
      spark-network:
        ipv4_address: 10.5.0.3      
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
      
  spark-worker-2:
    image: spark-worker
    restart: always
    container_name: spark-worker-2
    hostname: spark-worker-2
    ports:
      - 8082:8081
    env_file: ./spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks:
      spark-network:
        ipv4_address: 10.5.0.4      
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/24